apiVersion: v2
name: gitea
description: Gitea Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 1.16.7
icon: https://docs.gitea.io/images/gitea.png
keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - gitea
  - gogs
dependencies:
- name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: "> 5.9.0"
  condition: memcached.enabled
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: "> 6.14.10"
  condition: mysql.enabled
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: "> 10.3.17"
  condition: postgresql.enabled
- name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: "> 9.3.6"
  condition: mariadb.enabled
