---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitops-cert
  namespace: openshift-gitops
spec:
  # Name of the secret to hold the issued certificate
  secretName: openshift-gitops-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "Kinja"
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
  usages:
    - server auth
    - client auth
  dnsNames:
    - openshift-gitops-server-openshift-gitops.apps.{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}
  issuerRef:
    kind: ClusterIssuer
    name: cluster-local-issuer
    group: cert-manager.io
